platform: linux

image_resource:
  type: docker-image
  source:
     repository: trion/ng-cli-e2e

inputs:
- name: ng-concource-ci

caches:
- path: ng-concource-ci/node_modules

run:
  path: ./ng-concource-ci/ci/tasks/e2e.sh





