platform: linux

image_resource:
  type: docker-image
  source:
     repository: teracy/angular-cli

inputs:
- name: storage
- name: ng-concource-ci

outputs:
- name: build-out

run:
  path: ./ng-concource-ci/ci/tasks/release.sh





