resources:

- name: storage
  type: s3
  source:
    bucket: do-ju-concuorse
    regexp: web-app/ui
    access_key_id: AKIAJPBH4JHLGAABQDPA
    secret_access_key: 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

- name: ng-concource-ci
  type: git
  source:
    uri: https://github.com/do-mas/ng-concource-ci
    branch: s3

- name: staging-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: domas.juodele@gmail.com
    password: {password}
    organization: doju-pro
    space: development
    random-route: true

jobs:

- name: release
  plan:
  - aggregate:
    - get: storage
      trigger: true
      passed: [build]
  - task: build
    file: ng-concource-ci/ci/tasks/build.yml
  - put: staging-app
    params:
      manifest: build-out/manifest.yml
      path: build-out/root

- name: build
  plan:
  - aggregate:
    - get: ng-concource-ci
      trigger: true
  - task: build
    file: ng-concource-ci/ci/tasks/build.yml
  - put: storage
    params:
      file: build-out/manifest.yml

