resources:
- name: ng-concource-ci
  type: git
  source:
    uri: https://github.com/do-mas/ng-concource-ci
    branch: tests

- name: staging-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: domas.juodele@gmail.com
    password: {password}
    organization: doju-pro
    space: development
    random-route: true

jobs:

- name: unit-tests
  plan:
  - get: ng-concource-ci
    trigger: true
  - task: test
    file: ng-concource-ci/ci/tasks/test.yml

- name: e2e-tests
  plan:
  - get: ng-concource-ci
    trigger: true
  - task: e2e
    file: ng-concource-ci/ci/tasks/e2e.yml

- name: build
  plan:
  - aggregate:
    - get: ng-concource-ci
      trigger: true
      passed: [e2e-tests, unit-tests]
  - task: build
    file: ng-concource-ci/ci/tasks/build.yml
  - put: staging-app
    params:
      manifest: build-out/manifest.yml
      path: build-out/root

